/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DWC_H_RPCGEN
#define _DWC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *String;

struct DwcRequest {
	struct {
		u_int strings_len;
		String *strings_val;
	} strings;
};
typedef struct DwcRequest DwcRequest;

struct DwcResponse {
	int length;
	int total_words;
};
typedef struct DwcResponse DwcResponse;

#define dwc 55555555
#define VER 100

#if defined(__STDC__) || defined(__cplusplus)
#define count 1
extern  DwcResponse * count_100(DwcRequest *, CLIENT *);
extern  DwcResponse * count_100_svc(DwcRequest *, struct svc_req *);
extern int dwc_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define count 1
extern  DwcResponse * count_100();
extern  DwcResponse * count_100_svc();
extern int dwc_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_String (XDR *, String*);
extern  bool_t xdr_DwcRequest (XDR *, DwcRequest*);
extern  bool_t xdr_DwcResponse (XDR *, DwcResponse*);

#else /* K&R C */
extern bool_t xdr_String ();
extern bool_t xdr_DwcRequest ();
extern bool_t xdr_DwcResponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DWC_H_RPCGEN */
