/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dwc.h"

bool_t
xdr_Words (XDR *xdrs, Words *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->buffer, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_HashTable (XDR *xdrs, HashTable *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->capacity))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->strings, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_gnumbers (XDR *xdrs, gnumbers *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->g_assets))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->g_liabilities))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_gnumbers_node (XDR *xdrs, gnumbers_node *objp)
{
	register int32_t *buf;

	 if (!xdr_gnumbers (xdrs, &objp->gn_numbers))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->gn_next, sizeof (gnumbers_node), (xdrproc_t) xdr_gnumbers_node))
		 return FALSE;
	return TRUE;
}
