/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../lib/hashtable.h"
#include "dwc.h"

void build_response(DwcResponse* res, const HT* ht) {
    res->words_count.words_count_len = ht->size;
    res->words_count.words_count_val = (WordCount*)calloc(ht->size, sizeof(WordCount));

    int word_index = 0;
    for (int i = 0; i < ht->capacity; i++) {
        if (!HT_item_equals_null(ht->items[i])) {
            res->words_count.words_count_val[word_index].value = ht->items[i].value;
            res->words_count.words_count_val[word_index].key = ht->items[i].key;
            word_index++;
        }
    }
}

DwcResponse* count_100_svc(DwcRequest* req, struct svc_req* rqstp) {
    static DwcResponse response;
    int strings_len = req->strings.strings_len;
    HT* ht = HT_create();

    for (int i = 0; i < strings_len; i++) {
        HT_put(ht, req->strings.strings_val[i], i);
    }

    build_response(&response, ht);
    // for (int i = 0; i < response.words_count.words_count_len; i++) {
    //     printf("SERVER words_count_val[%d]: %s\n", i, response.words_count.words_count_val[i].key);
    // }   

    HT_destroy(ht);
    return &response;
}
