/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dwc.h"

bool_t
xdr_String (XDR *xdrs, String *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DwcRequest (XDR *xdrs, DwcRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->strings.strings_val, (u_int *) &objp->strings.strings_len, ~0,
		sizeof (String), (xdrproc_t) xdr_String))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DwcResponse (XDR *xdrs, DwcResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->total_words))
		 return FALSE;
	return TRUE;
}
