/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../lib/darray.h"
#include "../lib/hashtable.h"
#include "dwc.h"
#include "util.h"

DwcResponse* dwc_100(char* host, DwcRequest* req) {
    CLIENT* clnt;
    DwcResponse* response;

#ifndef DEBUG
    clnt = clnt_create(host, dwc, VER, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    response = count_100(req, clnt);
    if (response == (DwcResponse*)NULL) {
        clnt_perror(clnt, "call failed");
    }

#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
    return response;
}

int main(int argc, char* argv[]) {
    if (argc < 3) {
        printf("usage: %s <server_host> <file path>\n", argv[0]);
        exit(1);
    }

    char* host = argv[1];
    char* file_path = argv[2];
    Darray* darr = read_from_file(file_path);
    DwcRequest* req = DwcRequest_create_from_darray(darr);
    DwcResponse* res = dwc_100(host, req);

    int total_words = res->words_count.words_count_len;
    for (int i = 0; i < total_words; i++)
        printf("Word[%d]: %s, count %d\n", i, res->words_count.words_count_val[i].key, res->words_count.words_count_val[i].value);
    printf("Total words: %d\n", total_words);

    DwcRequest_destroy(req);
    DwcResponse_destroy(res);
    Darray_destroy(darr);
    return 0;
}
