/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../lib/darray.h"
#include "dwc.h"
#include "util.h"

void dwc_100(char* host, DwcRequest* dwc_req) {
    CLIENT* clnt;
    DwcResponse* result_1;

#ifndef DEBUG
    clnt = clnt_create(host, dwc, VER, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    result_1 = count_100(dwc_req, clnt);
    if (result_1 == (DwcResponse*)NULL) {
        clnt_perror(clnt, "call failed");
    }

    printf("Total words: %d\n", result_1->total_words);
#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char* argv[]) {
    char* host;

    if (argc < 2) {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }

    Darray* darr = Darray_create();
    char* strings[] = {
        "lorem",
        "ipsum",
        "coisa",
        "alem",
    };

    for (int i = 0; i < 4; i++) {
        Darray_append(darr, strings[i]);
    }

    DwcRequest* req = DwcRequest_create_from_darray(darr);

    host = argv[1];
    dwc_100(host, req);

    DwcRequest_destroy(req);
    Darray_destroy(darr);
    return 0;
}
