/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../lib/hashtable.h"
#include "dwc.h"

void DwcResponse_print(DwcResponse* res) {
    for (int i = 0; i < res->words_count.words_count_len; i++) {
        printf("Server words[%d]: %s -> %d\n", 
            i, res->words_count.words_count_val[i].key, res->words_count.words_count_val[i].value);
    }   
}

void build_response(DwcResponse* res, const HT* ht) {
    res->words_count.words_count_len = ht->size;
    res->words_count.words_count_val = (WordCount*)calloc(ht->size, sizeof(WordCount));

    int word_index = 0;
    for (int i = 0; i < ht->capacity; i++) {
        if (!HT_item_equals_null(ht->items[i])) {
            res->words_count.words_count_val[word_index].value = ht->items[i].value;
            res->words_count.words_count_val[word_index].key = ht->items[i].key;
            word_index++;
        }
    }
}

DwcResponse* count_100_svc(DwcRequest* req, struct svc_req* rqstp) {
    static DwcResponse response;
    int strings_len = req->strings.strings_len;
    HT* ht = HT_create();

    for (int i = 0; i < strings_len; i++) {
        int word_count = HT_get(ht, req->strings.strings_val[i]);
        if (word_count == _HT_ITEM_NULL_VAL) {
            HT_put(ht, req->strings.strings_val[i], 1);
        } else {
            HT_put(ht, req->strings.strings_val[i], word_count+1);
        }
    }

    printf("server received %d words\n", req->strings.strings_len);
    build_response(&response, ht);
    // DwcResponse_print(&response);
    HT_destroy(ht);
    return &response;
}
