/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"

void calculate_100(char *host, int x, int y) {
    CLIENT *clnt;
    int *result_1;
    int *result_2;
    operands add_100_arg = {x, y};
    operands sub_100_arg = {x, y};

#ifndef DEBUG
    clnt = clnt_create(host, calculate, VER, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    result_1 = add_100(&add_100_arg, clnt);
    if (result_1 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }
    result_2 = sub_100(&sub_100_arg, clnt);
    if (result_2 == (int *)NULL) {
        clnt_perror(clnt, "call failed");
    }

    printf("%d + %d = %d\n", x, y, *result_1);
    printf("%d - %d = %d\n", x, y, *result_2);

#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
    char *host;
    CLIENT *client;
    int x, y;

    if (argc != 4) {
        fprintf(stderr, "usage: %s <server_host> N1 N2\n", argv[0]);
        exit(1);
    }
    host = argv[1];

    x = atoi(argv[2]);
    y = atoi(argv[3]);

    calculate_100(host, x, y);
    exit(0);
}
