/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculate.h"
#include <memory.h> /* for memset */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = {25, 0};

int *add_100(operands *argp, CLIENT *clnt) {
    static int clnt_res;

    memset((char *)&clnt_res, 0, sizeof(clnt_res));
    if (clnt_call(clnt, add, (xdrproc_t)xdr_operands, (caddr_t)argp,
                  (xdrproc_t)xdr_int, (caddr_t)&clnt_res,
                  TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}

int *sub_100(operands *argp, CLIENT *clnt) {
    static int clnt_res;

    memset((char *)&clnt_res, 0, sizeof(clnt_res));
    if (clnt_call(clnt, sub, (xdrproc_t)xdr_operands, (caddr_t)argp,
                  (xdrproc_t)xdr_int, (caddr_t)&clnt_res,
                  TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}
