# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dwc_pb2 as dwc__pb2


class DistributedWordCounterStub(object):
    """Contador distribuído de palavras
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.count = channel.unary_unary(
                '/dwc.DistributedWordCounter/count',
                request_serializer=dwc__pb2.DwcRequest.SerializeToString,
                response_deserializer=dwc__pb2.DwcResponse.FromString,
                )


class DistributedWordCounterServicer(object):
    """Contador distribuído de palavras
    """

    def count(self, request, context):
        """Serviço que recebe Lista de palavras e dicionário de frequência 
        de palavras.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistributedWordCounterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'count': grpc.unary_unary_rpc_method_handler(
                    servicer.count,
                    request_deserializer=dwc__pb2.DwcRequest.FromString,
                    response_serializer=dwc__pb2.DwcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dwc.DistributedWordCounter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DistributedWordCounter(object):
    """Contador distribuído de palavras
    """

    @staticmethod
    def count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dwc.DistributedWordCounter/count',
            dwc__pb2.DwcRequest.SerializeToString,
            dwc__pb2.DwcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
