# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dwc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdwc.proto\x12\x03\x64wc\"\x1b\n\nDwcRequest\x12\r\n\x05words\x18\x01 \x03(\t\"\x80\x01\n\x0b\x44wcResponse\x12;\n\x0eword_frequency\x18\x01 \x03(\x0b\x32#.dwc.DwcResponse.WordFrequencyEntry\x1a\x34\n\x12WordFrequencyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\x46\n\x16\x44istributedWordCounter\x12,\n\x05\x63ount\x12\x0f.dwc.DwcRequest\x1a\x10.dwc.DwcResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DWCRESPONSE_WORDFREQUENCYENTRY._options = None
  _DWCRESPONSE_WORDFREQUENCYENTRY._serialized_options = b'8\001'
  _DWCREQUEST._serialized_start=18
  _DWCREQUEST._serialized_end=45
  _DWCRESPONSE._serialized_start=48
  _DWCRESPONSE._serialized_end=176
  _DWCRESPONSE_WORDFREQUENCYENTRY._serialized_start=124
  _DWCRESPONSE_WORDFREQUENCYENTRY._serialized_end=176
  _DISTRIBUTEDWORDCOUNTER._serialized_start=178
  _DISTRIBUTEDWORDCOUNTER._serialized_end=248
# @@protoc_insertion_point(module_scope)
